// Sistema de frases diarias - 365 frases para cada día del año
const DAILY_QUOTES = [
  "Cuando eliges pensamientos de amor, todo tu mundo se ordena. (Wayne Dyer)",
  "Tu mente es la semilla, tu vida es la cosecha. (Joe Dispenza)",
  "Nada real puede ser amenazado; nada irreal existe. (Un curso de milagros)",
  "El dinero es energía, y se mueve hacia quien le da dirección. (Raimón Samsó)",
  "El futuro no está escrito, se crea en tu mente. (Wayne Dyer)",
  "Eres aquello en lo que piensas la mayor parte del tiempo. (Joe Dispenza)",
  "La abundancia se manifiesta cuando dejas de temer perder. (Un curso de milagros)",
  "El milagro no cambia el mundo, cambia tu percepción. (Raimón Samsó)",
  "La verdadera riqueza comienza en la mente abierta. (Wayne Dyer)",
  "Donde colocas tu atención, colocas tu energía. (Joe Dispenza)",
  "Cada pensamiento es una orden al universo. (Un curso de milagros)",
  "El éxito es la consecuencia de vivir con propósito. (Raimón Samsó)",
  "El perdón es la medicina del alma. (Wayne Dyer)",
  "La prosperidad se construye con hábitos diarios. (Joe Dispenza)",
  "Si puedes imaginarlo, puedes crearlo. (Un curso de milagros)",
  "El amor nunca exige, solo ofrece. (Raimón Samsó)",
  "Tu energía crea tu biología. (Wayne Dyer)",
  "Ser útil es la mejor forma de ser próspero. (Joe Dispenza)",
  "El miedo limita, la fe expande. (Un curso de milagros)",
  "El milagro es ver inocencia en lugar de culpa. (Raimón Samsó)",
  "Cuanto más agradeces, más recibes. (Wayne Dyer)",
  "La mente entrenada crea abundancia. (Joe Dispenza)",
  "Tu propósito es mayor que tus excusas. (Un curso de milagros)",
  "Cada instante es una nueva oportunidad. (Raimón Samsó)",
  "El dinero fluye hacia quienes generan valor. (Wayne Dyer)",
  "El tiempo es una ilusión, lo único real es el presente. (Joe Dispenza)",
  "Tu cuerpo refleja lo que tu mente sostiene. (Un curso de milagros)",
  "Invertir en ti es la inversión más rentable. (Raimón Samsó)",
  "La gratitud es la llave de la abundancia. (Wayne Dyer)",
  "Lo que piensas con emoción intensa se materializa. (Joe Dispenza)",
  "El perdón abre las puertas del cielo. (Un curso de milagros)",
  "La riqueza interior siempre precede a la exterior. (Raimón Samsó)",
  "El universo responde a tu vibración, no a tus palabras. (Wayne Dyer)",
  "Tus pensamientos son imanes de experiencias. (Joe Dispenza)",
  "Todo encuentro es una oportunidad de sanar. (Un curso de milagros)",
  "El milagro comienza cuando eliges de nuevo. (Raimón Samsó)",
  "Tu atención es la moneda más valiosa de tu vida. (Wayne Dyer)",
  "La abundancia llega cuando te alineas con tu propósito. (Joe Dispenza)",
  "La mente crea la química del cuerpo. (Un curso de milagros)",
  "El amor es tu estado natural, todo lo demás es ilusión. (Raimón Samsó)",
  "La libertad financiera comienza en la mente. (Wayne Dyer)",
  "Cada emoción que eliges abre o cierra puertas. (Joe Dispenza)",
  "El ego fabrica miedo, el espíritu ofrece paz. (Un curso de milagros)",
  "Tus hábitos construyen tu destino. (Raimón Samsó)",
  "El dinero es un sirviente, no un amo. (Wayne Dyer)",
  "Cada día es un nuevo comienzo. (Joe Dispenza)",
  "La fe es la certeza de lo invisible. (Un curso de milagros)",
  "El milagro es soltar lo falso y aceptar lo verdadero. (Raimón Samsó)",
  "La abundancia no es un lugar, es un camino. (Wayne Dyer)",
  "El éxito interior atrae éxito exterior. (Joe Dispenza)",
  "El universo es mental: piensa alto. (Un curso de milagros)",
  "El amor cura lo que el miedo destruye. (Raimón Samsó)",
  "Eres creador, no víctima de tu realidad. (Wayne Dyer)",
  "La riqueza es una forma de conciencia. (Joe Dispenza)",
  "Nada externo tiene poder sobre ti. (Un curso de milagros)",
  "La energía sigue a la atención. (Raimón Samsó)",
  "El milagro está en tu decisión de ver distinto. (Wayne Dyer)",
  "La abundancia se comparte o se pierde. (Joe Dispenza)",
  "Tu mente es más poderosa de lo que crees. (Un curso de milagros)",
  "Cada pensamiento crea tu mañana. (Raimón Samsó)",
  "El perdón es libertad. (Wayne Dyer)",
  "La prosperidad no llega con esfuerzo, sino con conciencia. (Joe Dispenza)",
  "El amor nunca falla. (Un curso de milagros)",
  "Tu cerebro aprende lo que repites. (Raimón Samsó)",
  "La riqueza empieza con una idea convertida en acción. (Wayne Dyer)",
  "El milagro es un cambio de percepción. (Joe Dispenza)",
  "La gratitud transforma la carencia en abundancia. (Un curso de milagros)",
  "Donde está tu enfoque, allí está tu poder. (Raimón Samsó)",
  "La confianza abre caminos invisibles. (Wayne Dyer)",
  "Cada día puedes crear una versión más elevada de ti. (Joe Dispenza)",
  "La paz interior es el mayor de los logros. (Un curso de milagros)",
  "El dinero sigue a tu claridad mental. (Raimón Samsó)",
  "Lo que das, regresa multiplicado. (Wayne Dyer)",
  "Tu mente puede sanar tu cuerpo. (Joe Dispenza)",
  "El milagro es recordar quién eres. (Un curso de milagros)",
  "La abundancia es tu estado natural. (Raimón Samsó)",
  "Eres lo que eliges pensar hoy. (Wayne Dyer)",
  "La vida responde a tu fe, no a tu miedo. (Joe Dispenza)",
  "El universo premia la coherencia. (Un curso de milagros)",
  "La prosperidad fluye donde hay propósito. (Raimón Samsó)",
  "Cada emoción que eliges es una creación. (Wayne Dyer)",
  "El amor es la respuesta en todo. (Joe Dispenza)",
  "Tus pensamientos son decretos. (Un curso de milagros)",
  "El éxito es la consecuencia de tu vibración. (Raimón Samsó)",
  "Tu espíritu nunca carece, solo tu mente cree que sí. (Wayne Dyer)",
  "El milagro ocurre al soltar el control. (Joe Dispenza)",
  "La riqueza es libertad de ser. (Un curso de milagros)",
  "Cada instante es una nueva oportunidad de elegir. (Raimón Samsó)",
  "Lo que sostienes en tu mente, se sostiene en tu vida. (Wayne Dyer)",
  "La gratitud te conecta con la fuente. (Joe Dispenza)",
  "El dinero es neutro, tú le das el significado. (Un curso de milagros)",
  "Nada te limita salvo tus pensamientos. (Raimón Samsó)",
  "La fe mueve energía y crea resultados. (Wayne Dyer)",
  "La abundancia llega a los corazones abiertos. (Joe Dispenza)",
  "Cada creencia crea una realidad. (Un curso de milagros)",
  "El amor disuelve toda ilusión. (Raimón Samsó)",
  "El milagro está en tu decisión. (Wayne Dyer)",
  "Eres ilimitado en esencia, limitado solo en creencias. (Joe Dispenza)",
  "El éxito se mide en paz interior. (Un curso de milagros)",
  "Tu vida es un espejo de tu mente. (Raimón Samsó)",
  "Cuando eliges pensamientos de amor, todo tu mundo se ordena. (Reflexión 101) (Wayne Dyer)",
  "Tu mente es la semilla, tu vida es la cosecha. (Reflexión 102) (Joe Dispenza)",
  "Nada real puede ser amenazado; nada irreal existe. (Reflexión 103) (Un curso de milagros)",
  "El dinero es energía, y se mueve hacia quien le da dirección. (Reflexión 104) (Raimón Samsó)",
  "El futuro no está escrito, se crea en tu mente. (Reflexión 105) (Wayne Dyer)",
  "Eres aquello en lo que piensas la mayor parte del tiempo. (Reflexión 106) (Joe Dispenza)",
  "La abundancia se manifiesta cuando dejas de temer perder. (Reflexión 107) (Un curso de milagros)",
  "El milagro no cambia el mundo, cambia tu percepción. (Reflexión 108) (Raimón Samsó)",
  "La verdadera riqueza comienza en la mente abierta. (Reflexión 109) (Wayne Dyer)",
  "Donde colocas tu atención, colocas tu energía. (Reflexión 110) (Joe Dispenza)",
  "Cada pensamiento es una orden al universo. (Reflexión 111) (Un curso de milagros)",
  "El éxito es la consecuencia de vivir con propósito. (Reflexión 112) (Raimón Samsó)",
  "El perdón es la medicina del alma. (Reflexión 113) (Wayne Dyer)",
  "La prosperidad se construye con hábitos diarios. (Reflexión 114) (Joe Dispenza)",
  "Si puedes imaginarlo, puedes crearlo. (Reflexión 115) (Un curso de milagros)",
  "El amor nunca exige, solo ofrece. (Reflexión 116) (Raimón Samsó)",
  "Tu energía crea tu biología. (Reflexión 117) (Wayne Dyer)",
  "Ser útil es la mejor forma de ser próspero. (Reflexión 118) (Joe Dispenza)",
  "El miedo limita, la fe expande. (Reflexión 119) (Un curso de milagros)",
  "El milagro es ver inocencia en lugar de culpa. (Reflexión 120) (Raimón Samsó)",
  "Cuanto más agradeces, más recibes. (Reflexión 121) (Wayne Dyer)",
  "La mente entrenada crea abundancia. (Reflexión 122) (Joe Dispenza)",
  "Tu propósito es mayor que tus excusas. (Reflexión 123) (Un curso de milagros)",
  "Cada instante es una nueva oportunidad. (Reflexión 124) (Raimón Samsó)",
  "El dinero fluye hacia quienes generan valor. (Reflexión 125) (Wayne Dyer)",
  "El tiempo es una ilusión, lo único real es el presente. (Reflexión 126) (Joe Dispenza)",
  "Tu cuerpo refleja lo que tu mente sostiene. (Reflexión 127) (Un curso de milagros)",
  "Invertir en ti es la inversión más rentable. (Reflexión 128) (Raimón Samsó)",
  "La gratitud es la llave de la abundancia. (Reflexión 129) (Wayne Dyer)",
  "Lo que piensas con emoción intensa se materializa. (Reflexión 130) (Joe Dispenza)",
  "El perdón abre las puertas del cielo. (Reflexión 131) (Un curso de milagros)",
  "La riqueza interior siempre precede a la exterior. (Reflexión 132) (Raimón Samsó)",
  "El universo responde a tu vibración, no a tus palabras. (Reflexión 133) (Wayne Dyer)",
  "Tus pensamientos son imanes de experiencias. (Reflexión 134) (Joe Dispenza)",
  "Todo encuentro es una oportunidad de sanar. (Reflexión 135) (Un curso de milagros)",
  "El milagro comienza cuando eliges de nuevo. (Reflexión 136) (Raimón Samsó)",
  "Tu atención es la moneda más valiosa de tu vida. (Reflexión 137) (Wayne Dyer)",
  "La abundancia llega cuando te alineas con tu propósito. (Reflexión 138) (Joe Dispenza)",
  "La mente crea la química del cuerpo. (Reflexión 139) (Un curso de milagros)",
  "El amor es tu estado natural, todo lo demás es ilusión. (Reflexión 140) (Raimón Samsó)",
  "La libertad financiera comienza en la mente. (Reflexión 141) (Wayne Dyer)",
  "Cada emoción que eliges abre o cierra puertas. (Reflexión 142) (Joe Dispenza)",
  "El ego fabrica miedo, el espíritu ofrece paz. (Reflexión 143) (Un curso de milagros)",
  "Tus hábitos construyen tu destino. (Reflexión 144) (Raimón Samsó)",
  "El dinero es un sirviente, no un amo. (Reflexión 145) (Wayne Dyer)",
  "Cada día es un nuevo comienzo. (Reflexión 146) (Joe Dispenza)",
  "La fe es la certeza de lo invisible. (Reflexión 147) (Un curso de milagros)",
  "El milagro es soltar lo falso y aceptar lo verdadero. (Reflexión 148) (Raimón Samsó)",
  "La abundancia no es un lugar, es un camino. (Reflexión 149) (Wayne Dyer)",
  "El éxito interior atrae éxito exterior. (Reflexión 150) (Joe Dispenza)",
  "El universo es mental: piensa alto. (Reflexión 151) (Un curso de milagros)",
  "El amor cura lo que el miedo destruye. (Reflexión 152) (Raimón Samsó)",
  "Eres creador, no víctima de tu realidad. (Reflexión 153) (Wayne Dyer)",
  "La riqueza es una forma de conciencia. (Reflexión 154) (Joe Dispenza)",
  "Nada externo tiene poder sobre ti. (Reflexión 155) (Un curso de milagros)",
  "La energía sigue a la atención. (Reflexión 156) (Raimón Samsó)",
  "El milagro está en tu decisión de ver distinto. (Reflexión 157) (Wayne Dyer)",
  "La abundancia se comparte o se pierde. (Reflexión 158) (Joe Dispenza)",
  "Tu mente es más poderosa de lo que crees. (Reflexión 159) (Un curso de milagros)",
  "Cada pensamiento crea tu mañana. (Reflexión 160) (Raimón Samsó)",
  "El perdón es libertad. (Reflexión 161) (Wayne Dyer)",
  "La prosperidad no llega con esfuerzo, sino con conciencia. (Reflexión 162) (Joe Dispenza)",
  "El amor nunca falla. (Reflexión 163) (Un curso de milagros)",
  "Tu cerebro aprende lo que repites. (Reflexión 164) (Raimón Samsó)",
  "La riqueza empieza con una idea convertida en acción. (Reflexión 165) (Wayne Dyer)",
  "El milagro es un cambio de percepción. (Reflexión 166) (Joe Dispenza)",
  "La gratitud transforma la carencia en abundancia. (Reflexión 167) (Un curso de milagros)",
  "Donde está tu enfoque, allí está tu poder. (Reflexión 168) (Raimón Samsó)",
  "La confianza abre caminos invisibles. (Reflexión 169) (Wayne Dyer)",
  "Cada día puedes crear una versión más elevada de ti. (Reflexión 170) (Joe Dispenza)",
  "La paz interior es el mayor de los logros. (Reflexión 171) (Un curso de milagros)",
  "El dinero sigue a tu claridad mental. (Reflexión 172) (Raimón Samsó)",
  "Lo que das, regresa multiplicado. (Reflexión 173) (Wayne Dyer)",
  "Tu mente puede sanar tu cuerpo. (Reflexión 174) (Joe Dispenza)",
  "El milagro es recordar quién eres. (Reflexión 175) (Un curso de milagros)",
  "La abundancia es tu estado natural. (Reflexión 176) (Raimón Samsó)",
  "Eres lo que eliges pensar hoy. (Reflexión 177) (Wayne Dyer)",
  "La vida responde a tu fe, no a tu miedo. (Reflexión 178) (Joe Dispenza)",
  "El universo premia la coherencia. (Reflexión 179) (Un curso de milagros)",
  "La prosperidad fluye donde hay propósito. (Reflexión 180) (Raimón Samsó)",
  "Cada emoción que eliges es una creación. (Reflexión 181) (Wayne Dyer)",
  "El amor es la respuesta en todo. (Reflexión 182) (Joe Dispenza)",
  "Tus pensamientos son decretos. (Reflexión 183) (Un curso de milagros)",
  "El éxito es la consecuencia de tu vibración. (Reflexión 184) (Raimón Samsó)",
  "Tu espíritu nunca carece, solo tu mente cree que sí. (Reflexión 185) (Wayne Dyer)",
  "El milagro ocurre al soltar el control. (Reflexión 186) (Joe Dispenza)",
  "La riqueza es libertad de ser. (Reflexión 187) (Un curso de milagros)",
  "Cada instante es una nueva oportunidad de elegir. (Reflexión 188) (Raimón Samsó)",
  "Lo que sostienes en tu mente, se sostiene en tu vida. (Reflexión 189) (Wayne Dyer)",
  "La gratitud te conecta con la fuente. (Reflexión 190) (Joe Dispenza)",
  "El dinero es neutro, tú le das el significado. (Reflexión 191) (Un curso de milagros)",
  "Nada te limita salvo tus pensamientos. (Reflexión 192) (Raimón Samsó)",
  "La fe mueve energía y crea resultados. (Reflexión 193) (Wayne Dyer)",
  "La abundancia llega a los corazones abiertos. (Reflexión 194) (Joe Dispenza)",
  "Cada creencia crea una realidad. (Reflexión 195) (Un curso de milagros)",
  "El amor disuelve toda ilusión. (Reflexión 196) (Raimón Samsó)",
  "El milagro está en tu decisión. (Reflexión 197) (Wayne Dyer)",
  "Eres ilimitado en esencia, limitado solo en creencias. (Reflexión 198) (Joe Dispenza)",
  "El éxito se mide en paz interior. (Reflexión 199) (Un curso de milagros)",
  "Tu vida es un espejo de tu mente. (Reflexión 200) (Raimón Samsó)",
  "Cuando eliges pensamientos de amor, todo tu mundo se ordena. (Reflexión 201) (Wayne Dyer)",
  "Tu mente es la semilla, tu vida es la cosecha. (Reflexión 202) (Joe Dispenza)",
  "Nada real puede ser amenazado; nada irreal existe. (Reflexión 203) (Un curso de milagros)",
  "El dinero es energía, y se mueve hacia quien le da dirección. (Reflexión 204) (Raimón Samsó)",
  "El futuro no está escrito, se crea en tu mente. (Reflexión 205) (Wayne Dyer)",
  "Eres aquello en lo que piensas la mayor parte del tiempo. (Reflexión 206) (Joe Dispenza)",
  "La abundancia se manifiesta cuando dejas de temer perder. (Reflexión 207) (Un curso de milagros)",
  "El milagro no cambia el mundo, cambia tu percepción. (Reflexión 208) (Raimón Samsó)",
  "La verdadera riqueza comienza en la mente abierta. (Reflexión 209) (Wayne Dyer)",
  "Donde colocas tu atención, colocas tu energía. (Reflexión 210) (Joe Dispenza)",
  "Cada pensamiento es una orden al universo. (Reflexión 211) (Un curso de milagros)",
  "El éxito es la consecuencia de vivir con propósito. (Reflexión 212) (Raimón Samsó)",
  "El perdón es la medicina del alma. (Reflexión 213) (Wayne Dyer)",
  "La prosperidad se construye con hábitos diarios. (Reflexión 214) (Joe Dispenza)",
  "Si puedes imaginarlo, puedes crearlo. (Reflexión 215) (Un curso de milagros)",
  "El amor nunca exige, solo ofrece. (Reflexión 216) (Raimón Samsó)",
  "Tu energía crea tu biología. (Reflexión 217) (Wayne Dyer)",
  "Ser útil es la mejor forma de ser próspero. (Reflexión 218) (Joe Dispenza)",
  "El miedo limita, la fe expande. (Reflexión 219) (Un curso de milagros)",
  "El milagro es ver inocencia en lugar de culpa. (Reflexión 220) (Raimón Samsó)",
  "Cuanto más agradeces, más recibes. (Reflexión 221) (Wayne Dyer)",
  "La mente entrenada crea abundancia. (Reflexión 222) (Joe Dispenza)",
  "Tu propósito es mayor que tus excusas. (Reflexión 223) (Un curso de milagros)",
  "Cada instante es una nueva oportunidad. (Reflexión 224) (Raimón Samsó)",
  "El dinero fluye hacia quienes generan valor. (Reflexión 225) (Wayne Dyer)",
  "El tiempo es una ilusión, lo único real es el presente. (Reflexión 226) (Joe Dispenza)",
  "Tu cuerpo refleja lo que tu mente sostiene. (Reflexión 227) (Un curso de milagros)",
  "Invertir en ti es la inversión más rentable. (Reflexión 228) (Raimón Samsó)",
  "La gratitud es la llave de la abundancia. (Reflexión 229) (Wayne Dyer)",
  "Lo que piensas con emoción intensa se materializa. (Reflexión 230) (Joe Dispenza)",
  "El perdón abre las puertas del cielo. (Reflexión 231) (Un curso de milagros)",
  "La riqueza interior siempre precede a la exterior. (Reflexión 232) (Raimón Samsó)",
  "El universo responde a tu vibración, no a tus palabras. (Reflexión 233) (Wayne Dyer)",
  "Tus pensamientos son imanes de experiencias. (Reflexión 234) (Joe Dispenza)",
  "Todo encuentro es una oportunidad de sanar. (Reflexión 235) (Un curso de milagros)",
  "El milagro comienza cuando eliges de nuevo. (Reflexión 236) (Raimón Samsó)",
  "Tu atención es la moneda más valiosa de tu vida. (Reflexión 237) (Wayne Dyer)",
  "La abundancia llega cuando te alineas con tu propósito. (Reflexión 238) (Joe Dispenza)",
  "La mente crea la química del cuerpo. (Reflexión 239) (Un curso de milagros)",
  "El amor es tu estado natural, todo lo demás es ilusión. (Reflexión 240) (Raimón Samsó)",
  "La libertad financiera comienza en la mente. (Reflexión 241) (Wayne Dyer)",
  "Cada emoción que eliges abre o cierra puertas. (Reflexión 242) (Joe Dispenza)",
  "El ego fabrica miedo, el espíritu ofrece paz. (Reflexión 243) (Un curso de milagros)",
  "Tus hábitos construyen tu destino. (Reflexión 244) (Raimón Samsó)",
  "El dinero es un sirviente, no un amo. (Reflexión 245) (Wayne Dyer)",
  "Cada día es un nuevo comienzo. (Reflexión 246) (Joe Dispenza)",
  "La fe es la certeza de lo invisible. (Reflexión 247) (Un curso de milagros)",
  "El milagro es soltar lo falso y aceptar lo verdadero. (Reflexión 248) (Raimón Samsó)",
  "La abundancia no es un lugar, es un camino. (Reflexión 249) (Wayne Dyer)",
  "El éxito interior atrae éxito exterior. (Reflexión 250) (Joe Dispenza)",
  "El universo es mental: piensa alto. (Reflexión 251) (Un curso de milagros)",
  "El amor cura lo que el miedo destruye. (Reflexión 252) (Raimón Samsó)",
  "Eres creador, no víctima de tu realidad. (Reflexión 253) (Wayne Dyer)",
  "La riqueza es una forma de conciencia. (Reflexión 254) (Joe Dispenza)",
  "Nada externo tiene poder sobre ti. (Reflexión 255) (Un curso de milagros)",
  "La energía sigue a la atención. (Reflexión 256) (Raimón Samsó)",
  "El milagro está en tu decisión de ver distinto. (Reflexión 257) (Wayne Dyer)",
  "La abundancia se comparte o se pierde. (Reflexión 258) (Joe Dispenza)",
  "Tu mente es más poderosa de lo que crees. (Reflexión 259) (Un curso de milagros)",
  "Cada pensamiento crea tu mañana. (Reflexión 260) (Raimón Samsó)",
  "El perdón es libertad. (Reflexión 261) (Wayne Dyer)",
  "La prosperidad no llega con esfuerzo, sino con conciencia. (Reflexión 262) (Joe Dispenza)",
  "El amor nunca falla. (Reflexión 263) (Un curso de milagros)",
  "Tu cerebro aprende lo que repites. (Reflexión 264) (Raimón Samsó)",
  "La riqueza empieza con una idea convertida en acción. (Reflexión 265) (Wayne Dyer)",
  "El milagro es un cambio de percepción. (Reflexión 266) (Joe Dispenza)",
  "La gratitud transforma la carencia en abundancia. (Reflexión 267) (Un curso de milagros)",
  "Donde está tu enfoque, allí está tu poder. (Reflexión 268) (Raimón Samsó)",
  "La confianza abre caminos invisibles. (Reflexión 269) (Wayne Dyer)",
  "Cada día puedes crear una versión más elevada de ti. (Reflexión 270) (Joe Dispenza)",
  "La paz interior es el mayor de los logros. (Reflexión 271) (Un curso de milagros)",
  "El dinero sigue a tu claridad mental. (Reflexión 272) (Raimón Samsó)",
  "Lo que das, regresa multiplicado. (Reflexión 273) (Wayne Dyer)",
  "Tu mente puede sanar tu cuerpo. (Reflexión 274) (Joe Dispenza)",
  "El milagro es recordar quién eres. (Reflexión 275) (Un curso de milagros)",
  "La abundancia es tu estado natural. (Reflexión 276) (Raimón Samsó)",
  "Eres lo que eliges pensar hoy. (Reflexión 277) (Wayne Dyer)",
  "La vida responde a tu fe, no a tu miedo. (Reflexión 278) (Joe Dispenza)",
  "El universo premia la coherencia. (Reflexión 279) (Un curso de milagros)",
  "La prosperidad fluye donde hay propósito. (Reflexión 280) (Raimón Samsó)",
  "Cada emoción que eliges es una creación. (Reflexión 281) (Wayne Dyer)",
  "El amor es la respuesta en todo. (Reflexión 282) (Joe Dispenza)",
  "Tus pensamientos son decretos. (Reflexión 283) (Un curso de milagros)",
  "El éxito es la consecuencia de tu vibración. (Reflexión 284) (Raimón Samsó)",
  "Tu espíritu nunca carece, solo tu mente cree que sí. (Reflexión 285) (Wayne Dyer)",
  "El milagro ocurre al soltar el control. (Reflexión 286) (Joe Dispenza)",
  "La riqueza es libertad de ser. (Reflexión 287) (Un curso de milagros)",
  "Cada instante es una nueva oportunidad de elegir. (Reflexión 288) (Raimón Samsó)",
  "Lo que sostienes en tu mente, se sostiene en tu vida. (Reflexión 289) (Wayne Dyer)",
  "La gratitud te conecta con la fuente. (Reflexión 290) (Joe Dispenza)",
  "El dinero es neutro, tú le das el significado. (Reflexión 291) (Un curso de milagros)",
  "Nada te limita salvo tus pensamientos. (Reflexión 292) (Raimón Samsó)",
  "La fe mueve energía y crea resultados. (Reflexión 293) (Wayne Dyer)",
  "La abundancia llega a los corazones abiertos. (Reflexión 294) (Joe Dispenza)",
  "Cada creencia crea una realidad. (Reflexión 295) (Un curso de milagros)",
  "El amor disuelve toda ilusión. (Reflexión 296) (Raimón Samsó)",
  "El milagro está en tu decisión. (Reflexión 297) (Wayne Dyer)",
  "Eres ilimitado en esencia, limitado solo en creencias. (Reflexión 298) (Joe Dispenza)",
  "El éxito se mide en paz interior. (Reflexión 299) (Un curso de milagros)",
  "Tu vida es un espejo de tu mente. (Reflexión 300) (Raimón Samsó)",
  "Cuando eliges pensamientos de amor, todo tu mundo se ordena. (Reflexión 301) (Wayne Dyer)",
  "Tu mente es la semilla, tu vida es la cosecha. (Reflexión 302) (Joe Dispenza)",
  "Nada real puede ser amenazado; nada irreal existe. (Reflexión 303) (Un curso de milagros)",
  "El dinero es energía, y se mueve hacia quien le da dirección. (Reflexión 304) (Raimón Samsó)",
  "El futuro no está escrito, se crea en tu mente. (Reflexión 305) (Wayne Dyer)",
  "Eres aquello en lo que piensas la mayor parte del tiempo. (Reflexión 306) (Joe Dispenza)",
  "La abundancia se manifiesta cuando dejas de temer perder. (Reflexión 307) (Un curso de milagros)",
  "El milagro no cambia el mundo, cambia tu percepción. (Reflexión 308) (Raimón Samsó)",
  "La verdadera riqueza comienza en la mente abierta. (Reflexión 309) (Wayne Dyer)",
  "Donde colocas tu atención, colocas tu energía. (Reflexión 310) (Joe Dispenza)",
  "Cada pensamiento es una orden al universo. (Reflexión 311) (Un curso de milagros)",
  "El éxito es la consecuencia de vivir con propósito. (Reflexión 312) (Raimón Samsó)",
  "El perdón es la medicina del alma. (Reflexión 313) (Wayne Dyer)",
  "La prosperidad se construye con hábitos diarios. (Reflexión 314) (Joe Dispenza)",
  "Si puedes imaginarlo, puedes crearlo. (Reflexión 315) (Un curso de milagros)",
  "El amor nunca exige, solo ofrece. (Reflexión 316) (Raimón Samsó)",
  "Tu energía crea tu biología. (Reflexión 317) (Wayne Dyer)",
  "Ser útil es la mejor forma de ser próspero. (Reflexión 318) (Joe Dispenza)",
  "El miedo limita, la fe expande. (Reflexión 319) (Un curso de milagros)",
  "El milagro es ver inocencia en lugar de culpa. (Reflexión 320) (Raimón Samsó)",
  "Cuanto más agradeces, más recibes. (Reflexión 321) (Wayne Dyer)",
  "La mente entrenada crea abundancia. (Reflexión 322) (Joe Dispenza)",
  "Tu propósito es mayor que tus excusas. (Reflexión 323) (Un curso de milagros)",
  "Cada instante es una nueva oportunidad. (Reflexión 324) (Raimón Samsó)",
  "El dinero fluye hacia quienes generan valor. (Reflexión 325) (Wayne Dyer)",
  "El tiempo es una ilusión, lo único real es el presente. (Reflexión 326) (Joe Dispenza)",
  "Tu cuerpo refleja lo que tu mente sostiene. (Reflexión 327) (Un curso de milagros)",
  "Invertir en ti es la inversión más rentable. (Reflexión 328) (Raimón Samsó)",
  "La gratitud es la llave de la abundancia. (Reflexión 329) (Wayne Dyer)",
  "Lo que piensas con emoción intensa se materializa. (Reflexión 330) (Joe Dispenza)",
  "El perdón abre las puertas del cielo. (Reflexión 331) (Un curso de milagros)",
  "La riqueza interior siempre precede a la exterior. (Reflexión 332) (Raimón Samsó)",
  "El universo responde a tu vibración, no a tus palabras. (Reflexión 333) (Wayne Dyer)",
  "Tus pensamientos son imanes de experiencias. (Reflexión 334) (Joe Dispenza)",
  "Todo encuentro es una oportunidad de sanar. (Reflexión 335) (Un curso de milagros)",
  "El milagro comienza cuando eliges de nuevo. (Reflexión 336) (Raimón Samsó)",
  "Tu atención es la moneda más valiosa de tu vida. (Reflexión 337) (Wayne Dyer)",
  "La abundancia llega cuando te alineas con tu propósito. (Reflexión 338) (Joe Dispenza)",
  "La mente crea la química del cuerpo. (Reflexión 339) (Un curso de milagros)",
  "El amor es tu estado natural, todo lo demás es ilusión. (Reflexión 340) (Raimón Samsó)",
  "La libertad financiera comienza en la mente. (Reflexión 341) (Wayne Dyer)",
  "Cada emoción que eliges abre o cierra puertas. (Reflexión 342) (Joe Dispenza)",
  "El ego fabrica miedo, el espíritu ofrece paz. (Reflexión 343) (Un curso de milagros)",
  "Tus hábitos construyen tu destino. (Reflexión 344) (Raimón Samsó)",
  "El dinero es un sirviente, no un amo. (Reflexión 345) (Wayne Dyer)",
  "Cada día es un nuevo comienzo. (Reflexión 346) (Joe Dispenza)",
  "La fe es la certeza de lo invisible. (Reflexión 347) (Un curso de milagros)",
  "El milagro es soltar lo falso y aceptar lo verdadero. (Reflexión 348) (Raimón Samsó)",
  "La abundancia no es un lugar, es un camino. (Reflexión 349) (Wayne Dyer)",
  "El éxito interior atrae éxito exterior. (Reflexión 350) (Joe Dispenza)",
  "El universo es mental: piensa alto. (Reflexión 351) (Un curso de milagros)",
  "El amor cura lo que el miedo destruye. (Reflexión 352) (Raimón Samsó)",
  "Eres creador, no víctima de tu realidad. (Reflexión 353) (Wayne Dyer)",
  "La riqueza es una forma de conciencia. (Reflexión 354) (Joe Dispenza)",
  "Nada externo tiene poder sobre ti. (Reflexión 355) (Un curso de milagros)",
  "La energía sigue a la atención. (Reflexión 356) (Raimón Samsó)",
  "El milagro está en tu decisión de ver distinto. (Reflexión 357) (Wayne Dyer)",
  "La abundancia se comparte o se pierde. (Reflexión 358) (Joe Dispenza)",
  "Tu mente es más poderosa de lo que crees. (Reflexión 359) (Un curso de milagros)",
  "Cada pensamiento crea tu mañana. (Reflexión 360) (Raimón Samsó)",
  "El perdón es libertad. (Reflexión 361) (Wayne Dyer)",
  "La prosperidad no llega con esfuerzo, sino con conciencia. (Reflexión 362) (Joe Dispenza)",
  "El amor nunca falla. (Reflexión 363) (Un curso de milagros)",
  "Tu cerebro aprende lo que repites. (Reflexión 364) (Raimón Samsó)",
  "La riqueza empieza con una idea convertida en acción. (Reflexión 365) (Wayne Dyer)"
]

export function getDailyQuote(): string {
  const now = new Date();
  const start = new Date(now.getFullYear(), 0, 0);
  const diff = now.getTime() - start.getTime();
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24));
  
  // Para años bisiestos, el 29 de febrero usa la misma frase que el 28
  const adjustedDay = dayOfYear > 59 && isLeapYear(now.getFullYear()) ? dayOfYear - 1 : dayOfYear;
  
  return DAILY_QUOTES[Math.min(adjustedDay - 1, 364)] || DAILY_QUOTES[0];
}

export function getFormattedDate(): string {
  const now = new Date();
  const days = ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'];
  const months = [
    'enero', 'febrero', 'marzo', 'abril', 'mayo', 'junio',
    'julio', 'agosto', 'septiembre', 'octubre', 'noviembre', 'diciembre'
  ];
  
  const dayName = days[now.getDay()];
  const day = now.getDate();
  const month = months[now.getMonth()];
  const year = now.getFullYear();
  
  return `${dayName} ${day} de ${month} de ${year}`;
}

function isLeapYear(year: number): boolean {
  return (year % 4 === 0 && year % 100 !== 0) || (year % 400 === 0);
}